import "pkg:/utils.bs"
const OMDB_API_URL = getConfigVar("apiConfig.OMDB.API")
const OMDB_API_KEY = getEnvVar("api.OMDB.API_KEY")

sub init()
    m.top.id = "PosterView"
    bindComponents()
    hookObservers()
    setStyles()
end sub

sub bindComponents()
    m.poster = m.top.findNode("poster")
    m.divider = m.top.findNode("divider")
    m.secondHalfGroup = m.top.findNode("secondHalfGroup")
    m.contentTitle = m.top.findNode("contentTitle")
    m.contentYear = m.top.findNode("contentYear")
    m.contentDescription = m.top.findNode("contentDescription")
    m.playButton = m.top.findNode("playButton")
    m.requestsTask = createObject("roSGNode", "RequestsTask")
end sub

sub hookObservers()
    m.top.observeField("visible", "onVisibleChange")
    m.top.observeField("imdbid", "requestTitleDetails")
    m.requestsTask.observeField("response", "onTitleResponse")
    m.playButton.observeField("buttonSelected", "onPlayButtonSelected")
end sub

sub setStyles()
    sqMarginSmall = 100
    sqMarginBig = sqMarginSmall * 2
    sectorWidth = 550
    ' Should set some rules here to make it play well taking display
    ' size and using rule of thirds to calculate the sizes

    ' TBD: Create a mask for the posters, maybe..
    m.poster.translation = [ sqMarginBig, sqMarginBig ]
    m.poster.width = sectorWidth

    m.divider.translation = [ 959, sqMarginBig ]
    m.divider.width = 2 ' Should be even to make it symmetrical in position
    m.divider.height = 960
    m.divider.color = "0xD3D3D3FF"

    m.secondHalfGroup.translation = [ sqMarginSmall + 1066, sqMarginBig ]
    m.secondHalfGroup.itemSpacings = [ 27 ] ' Check if only for the vertical placement is ok

    m.contentTitle.width = 426
    m.contentTitle.font  = createObject("roSGNode", "Font")
    m.contentTitle.font.uri = "pkg:/fonts/Gotham-Bold.otf"
    m.contentTitle.font.size = 36

    m.contentYear.translation = [ sqMarginBig, 120 ]
    m.contentYear.width = 426
    m.contentYear.font  = createObject("roSGNode", "Font")
    m.contentYear.font.uri = "pkg:/fonts/Gotham-Bold.otf"
    m.contentYear.font.size = 24

    m.contentDescription.translation = [ sqMarginBig, 150 ]
    m.contentDescription.width = 426
    m.contentDescription.height = 491
    m.contentDescription.ellipsizeOnBoundary = true
    m.contentDescription.wrap = true
    m.contentDescription.font  = createObject("roSGNode", "Font")
    m.contentDescription.font.uri = "pkg:/fonts/Gotham-Book.otf"
    m.contentDescription.font.size = 20

    m.playButton.translation = [ 1440, 650 ]
    m.playButton.config = {
        bgWidth: 300
        bgHeight: 80
        fontSize: 30
        text: "Play Video"
    }
end sub

sub onVisibleChange(event as Object)
    visible = event.getData()
    if visible then m.playButton.setFocus(true)
end sub

sub requestTitleDetails(event as Object)
    imdbid = event.getData()
    m.requestsTask.request = {
        method: "GET"
        url: OMDB_API_URL
        params: {
            apikey: OMDB_API_KEY
            i: imdbid
            plot: "full"
        }
    }
    m.requestsTask.control = "run"
end sub

sub onTitleResponse(event as Object)
    m.requestsTask.control = "stop"
    response = event.getData()
    responseBody = response.responseBody
    if responseBody.response = "False"
        print `ROTT Error: Component ${m.top.id} : OMDB Request : Response error ${responseBody["Error"]}`
        return
    end if
    m.poster.uri = responseBody["Poster"]
    m.contentTitle.text = responseBody["Title"]
    m.contentYear.text = responseBody["Year"]
    m.contentDescription.text = responseBody["Plot"]

    m.playButton.setFocus(true)
end sub

sub onPlayButtonSelected()
    m.top.playVideo = invalid
end sub

function onKeyEvent(key as String, press as Boolean) as Boolean
    if not press then return false
    if key = "back"
        m.top.close = true
        return true
    end if
    return false
end function
